name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.7.0
      - name: Install Next.js
        run: |
          npm ci
      - name: Deploy GitHub Pages
        run: |
          npm run build
          npm run export
          git worktree add gh-pages gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../out/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force
